services:
  server:
    container_name: movie_booking_api
    build:
      context: .
      target: development
    ports:
      - 8080:8080
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - movie_booking
    develop:
      watch:
        - action: rebuild
          path: .
  db:
    container_name: mysql_db
    image: minhquang3010/movie_booking_database:1.1
    restart: always
    volumes:
      - mysql-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=movie_ticket_booking
      - MYSQL_USER=movie_ticket_booking
      - MYSQL_PASSWORD=movie_ticket_booking
    ports:
      - 3309:3306
    networks:
      - movie_booking
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "movie_ticket_booking", "--password=movie_ticket_booking"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  movie_booking:
    driver: bridge
volumes:
  mysql-db-data:
    driver: local